### PR TITLE
Settings reworked and retainer overlay extended

### PR DESCRIPTION
**Pull request by xPumaa**
Had this in the pipeline too. If don't you like it, screw it.

Settings:
image

Overlay:
image

### CODE REVIEW

**Comment by chalkos** [comment]
I could add the gil undercut to the overlay as well.
And `ImGuiHelpers.GlobalScale` is always good to have.
But that would be added in, not merged.
also i forgot to give you credit for the gil undercut, gonna do that.

Have you looked at the new UI? what do you think?

**Comment by xPumaa** [comment]
I like it much better than my version, but please always show "the limit stack size" in the overlay or make an option for it.
Sometimes I want to limit the stack size and then it is quite nasty to have to go into the settings first.

It would be very nice if the gil undercut was in the overlay.

I also looked in the code and please don't forget to save the gil undercut
https://github.com/chalkos/Marketbuddy/blob/9752fd579184d357befa70a37986e3fc81ce061c/Marketbuddy/PluginUI.cs#L117

**Comment by chalkos** [comment]
> I like it much better than my version, but please always show "the limit stack size" in the overlay or make an option for it.
> Sometimes I want to limit the stack size and then it is quite nasty to have to go into the settings first.

welp.. this was not intentional. it should have been as you described. i forgot that there was also a checkbox linked to the same bool in the overlay... and screwed that up because the overlay gets disabled when you're not limiting anymore :|

> It would be very nice if the gil undercut was in the overlay.
ye I'll fix the above and add this in the same go

> I also looked in the code and please don't forget to save the gil undercut
I clearly need to test this more before i release. good catch!

**Comment by chalkos** [comment]
and done. hopefully I stopped breaking things now and managed to add a few cool things along the way 😅

**Comment by xPumaa** [comment]
Nice. I'm closing the PR now.

One note, maybe also allow 0 as a value for undercut gil.
I have heard from many people that they always set the price as low as possible without undercutting it.

**Pull request closed without merging**
